export const PokeTypeList = [
  "Normal",
  "Fire",
  "Water",
  "Grass",
  "Electric",
  "Ice",
  "Fighting",
  "Poison",
  "Ground",
  "Flying",
  "Psychic",
  "Bug",
  "Rock",
  "Ghost",
  "Dragon",
  "Dark",
  "Steel",
  "Fairy",
];

export const PokeTypeIndex = {
  Normal: 0,
  Fire: 1,
  Water: 2,
  Grass: 3,
  Electric: 4,
  Ice: 5,
  Fighting: 6,
  Poison: 7,
  Ground: 8,
  Flying: 9,
  Psychic: 10,
  Bug: 11,
  Rock: 12,
  Ghost: 13,
  Dragon: 14,
  Dark: 15,
  Steel: 16,
  Fairy: 17,
};

export const PokeTypeColor = {
  Normal: "#949495",
  Fire: "#e56c3e",
  Water: "#5185c5",
  Grass: "#66a945",
  Electric: "#f6d851",
  Ice: "#6dc8eb",
  Fighting: "#e09c40",
  Poison: "#735198",
  Ground: "#9c7743",
  Flying: "#a2c3e7",
  Psychic: "#dd6b7b",
  Bug: "#9fa244",
  Rock: "#bfb889",
  Ghost: "#684870",
  Dragon: "#535ca8",
  Dark: "#4c4948",
  Steel: "#69a9c7",
  Fairy: "#dab4d4",
};

export const PokeTypeKor = {
  Normal: "노말",
  Fire: "불",
  Water: "물",
  Grass: "풀",
  Electric: "전기",
  Ice: "얼음",
  Fighting: "격투",
  Poison: "독",
  Ground: "땅",
  Flying: "비행",
  Psychic: "에스퍼",
  Bug: "벌레",
  Rock: "바위",
  Ghost: "고스트",
  Dragon: "드래곤",
  Dark: "악",
  Steel: "강철",
  Fairy: "페어리",
};

export const DamageLabelArray = ["×8", "×4", "×2", "÷2", "÷4", "÷8", "0"];
